// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc_15k0eG8YHhpBCd3DN6_Ao8ScQGUxLI',
    appId: '1:279121306393:web:bfa26ddec5c9f426075b88',
    messagingSenderId: '279121306393',
    projectId: 'csiauthentication-54e0a',
    authDomain: 'csiauthentication-54e0a.firebaseapp.com',
    storageBucket: 'csiauthentication-54e0a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIWgqSf8_vBfwiuSadErGaQLyEeBqdIlU',
    appId: '1:279121306393:android:a419a22c2a3aeb8d075b88',
    messagingSenderId: '279121306393',
    projectId: 'csiauthentication-54e0a',
    storageBucket: 'csiauthentication-54e0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_LY0KVkM9vWWkAIH5W7pMB2wN0u77X-s',
    appId: '1:279121306393:ios:b30313a94a339a26075b88',
    messagingSenderId: '279121306393',
    projectId: 'csiauthentication-54e0a',
    storageBucket: 'csiauthentication-54e0a.appspot.com',
    iosClientId: '279121306393-pptubbcer7q3kv53te4uh62t38n1bg0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.acmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_LY0KVkM9vWWkAIH5W7pMB2wN0u77X-s',
    appId: '1:279121306393:ios:7d5d90a3080bc73f075b88',
    messagingSenderId: '279121306393',
    projectId: 'csiauthentication-54e0a',
    storageBucket: 'csiauthentication-54e0a.appspot.com',
    iosClientId: '279121306393-pl4sqefug3k7n26ga1vecpek9g7guucc.apps.googleusercontent.com',
    iosBundleId: 'com.example.acmApp.RunnerTests',
  );
}
